webtalk_init -webtalk_dir C:/Users/warre/Documents/space_invaders_stukken/space_invaders_stukken.sim/sim_1/behav/xsim/xsim.dir/tb_debouncer_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Dec 24 11:48:04 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7e412a86-4c75-489b-a16f-797baed969b8" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "951409424f1348eb9d4b854b98d364ee" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 8940HX with Radeon Graphics        " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2395 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "12001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.17_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "20052_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4133721947 -regid "" -xml C:/Users/warre/Documents/space_invaders_stukken/space_invaders_stukken.sim/sim_1/behav/xsim/xsim.dir/tb_debouncer_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/warre/Documents/space_invaders_stukken/space_invaders_stukken.sim/sim_1/behav/xsim/xsim.dir/tb_debouncer_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/warre/Documents/space_invaders_stukken/space_invaders_stukken.sim/sim_1/behav/xsim/xsim.dir/tb_debouncer_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
